### ISSUE TITLE
transform issues

### ISSUE THREAD

**Issue by MariusAlch** [shakyShane/json-ts#5]
// name and dame should both be optional
```json
{
  "thing": [{"name": "darius"}, {"dame": 42}]
}
```
//invalid interface name if used without prefix
```json
{
  "231thing": [{"name": "darius"}, {"dame": 42}]
}
```

**Comment by shakyShane** [comment]
thanks @MariusAlch 

the first item is [fixed now](https://shakyshane.github.io/json-ts/#src=%7B%0A%22thing%22%3A%20%5B%7B%22name%22%3A%20%22darius%22%7D%2C%20%7B%22dame%22%3A%2042%7D%5D%0A%7D)

The second is indeed still a bug, thanks for pointing it out :)
