### ISSUE TITLE
"How does json-ts stack up against the competition?" table out of date

### ISSUE THREAD

**Issue by MariusAlch** [shakyShane/json-ts#6]
Author of "json-to-ts".

If you are going to have comparison table please add library versions or date.

currently "json-to-ts" supports union types + "nested type literals (to account for invalid interface names)" should be working fine with "json-to-ts"

Off topic: No hard feelings, impresive app, keep it going! :)

**Comment by shakyShane** [comment]
@MariusAlch update json-to-ts to include now

```
array union types
website
nested type literals
```

I just landed the ability to merge multiple json inputs (in the table), let me know if/when json-to-ts supports that and I'll update again
