### ISSUE TITLE
Incorrect capitalisation 

### ISSUE THREAD

**Issue by tm1303** [shakyShane/json-ts#8]
Hello,

When capitalising an item that has been appended with _Item_ the capitalisation from the json source is lost.

My C# poco...
`public IEnumerable<Job> OpenJobs { get; set; }`

The api output...
`openJobs: [ ... ]`

The output from json-ts...
`export interface OpenjobsItem { ... }`

I'd expect the output to be 
`export interface OpenJobsItem { ... }`

Thanks!

**Comment by tm1303** [comment]
have a fix, will open a pull request.

**Comment by shakyShane** [comment]
Fixed via https://github.com/shakyShane/json-ts/pull/9
